version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"  # Expose n8n port
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin      # 🔒 Change this
      - N8N_BASIC_AUTH_PASSWORD=strongpassword  # 🔒 Change this
      - WEBHOOK_URL=https://yourdomain.com/  # 🔗 Or your public IP if testing
      - N8N_HOST=yourdomain.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - TZ=Asia/Kolkata
    volumes:
      - n8n_data:/home/node/.n8n  # 🗃 Persistent workflows, credentials, etc.

volumes:
  n8n_data:
